### ISSUE TITLE
Create right side panel for indicators for 2.23

### ISSUE THREAD

**Issue by adrianq** [EyeSeeTea/maintenance-app#1]
- [x] Create drawer component
- [x] Implement CategoryOptionCombinationDraw
   - [x] Add CategoryCombination Combobox
   - [x] Add CategoryOption Combobox
   - [x] Retrieve CategoryOptionCombination
   - [x] Add Ok button and update indicator field
- [x] Embed into indicator component
- [x] Cosmetics

**Comment by adrianq** [comment]
@jferrettiboke Please find below a more detailed list of everything that needs to be fixed/improved in the side panel:
- [x] Right side panel should only be opened for elements with two uids.  e.g. it shouldn't open for "Malaria (Total)" (#{uid}) but it should open for "Malaria, <15y" (#{uid1.uid2}). If you double click on any of them you can see what I mean.  It should be opened on click as it is currently happening.
- [x] Title for the drawer should be hardcoded to "Dataset Attribute Combination". We are gonna keep the AppBar on top as this is actually the look&feel for drawers on the next material-ui release.
- [x]  Add Ok button at the bottom. We will discuss the functionality on Tuesday
- [x]  Title for the first dropdown is fine however we  need to change titles for the others dropdowns (the ones that appear after an option is selected for the first one). Instead of "Choose Category" we should have "Choose [Category] where [Category] should be the displayedName of the category, i.e. "Choose Donor" or "Choose Project".
- [x] Validation:
   - [x] Double click functionality should have the same functionality even if the right panel is opened
   - [x] If we don't choose  anything on the first dropdown "Choose Category Combo" Ok button should be available and  should have the same behaviour as  when we double click on an element
   - [x] If anything has been selected on the first dropdown user will have to fill the rest of the dropdowns. Otherwise dropdown should be disabled
- [ ] Height for the drawer panel should be the same as for the dataElements panel
- [x] Better layout
- [x] Refactor code
- [ ] Enlarge the white popup where the indicators creation screen is being represented to almost take all the screen. This way, we would avoid wasting space now that we're including this extra panel.

@ifoche I have tried to sum up what we discuss, feel free to add/modify anything!
@jferrettiboke Give me a shout if anything is not clear! And feel free as well to change or add anything at your convenience!

**Comment by jferrettiboke** [comment]
Cool. Pretty straightforward explanation. I will work on this.

**Comment by ifoche** [comment]
@adrianq I've reviewed it and it looks like almost everything's there and perfectly explained. I would only add a little clarification and one thing that's missing.

- The clarification is for the first point. Just for the record, please @jferrettiboke note that 2 UIDs doesn't mean 2 elements in the combination. I'm sure you're already aware of that. 
Malaria (Total) can be defined with only 1 UID, and "Malaria, <15y" has 2 UIDs, but "Malaria, <15y, Male" is also 2 UIDs and could even have very large combination like "Malaria, <15y, Male, fever, 2kg," and will still be a 2 UIDs element. The point is Malaria is the DE, and the rest are just combinations (and all combination of options is always represented with a single UID).

- The subtask missing would be to enlarge the white popup where the indicators creation screen is being represented to almost take all the screen. This way, we would avoid wasting space now that we're including this extra panel.

I hope it's clear, but please let me know if something's not very well explained.

**Comment by adrianq** [comment]
Most of the tasks for this card  are done. Enough for a demo. Bits missing:
- [ ] Enlarge the white popup where the indicators creation screen is being represented to almost take all the screen. This way, we would avoid wasting space now that we're including this extra panel.
- [ ] I am not 100% happy with the solution implemented for the height. Probably good enough for now but something better will need to be done for 2.25
- [ ] Refactor a bit the code and comment it better.
